name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux]
        arch: [amd64, 386, arm64]
        exclude:
          - os: windows
            arch: arm64
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v -o myapp-${{ matrix.os }}-${{ matrix.arch }} ./main.go
      env:
        CGO_ENABLED: 0

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: myapp-${{ matrix.os }}-${{ matrix.arch }}
        path: myapp-${{ matrix.os }}-${{ matrix.arch }}

    - name: Run
      if: matrix.os == 'linux' && matrix.arch == 'amd64'
      run: |
        chmod +x ./myapp-${{ matrix.os }}-${{ matrix.arch }}
        ./myapp-${{ matrix.os }}-${{ matrix.arch }}
