name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64, 386]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o myapp-${{ matrix.goos }}-${{ matrix.goarch }} ./main.go

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: myapp-${{ matrix.goos }}-${{ matrix.goarch }}
        path: myapp-${{ matrix.goos }}-${{ matrix.goarch }}
